import './globals.css'
import AnimatedBlob from '../components/AnimatedBlob';
import AnimatedWave from '../components/AnimatedWave';
import AnimatedParticles from '../components/AnimatedParticles';

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }) {
 return (
    <html lang="en">
      <head>
        <link rel="icon" href="/logo_gudkid.png" />
      </head>
      <body style={{ position: 'relative', minHeight: '100vh', overflowX: 'hidden' }}>
        {/* Animated Blobs di background */}
        <div style={{ position: 'fixed', top: 0, left: 0, width: '100vw', height: '100vh', zIndex: 0, pointerEvents: 'none' }}>
          <AnimatedBlob />
          <AnimatedParticles />
        </div>
        {/* Main Content */}
        <div style={{ position: 'relative', zIndex: 2 }}>
          {children}
        </div>
        {/* Animated Wave di paling bawah */}
        <div style={{ position: 'fixed', bottom: 0, left: 0, width: '100vw', zIndex: 1, pointerEvents: 'none' }}>
          <AnimatedWave />
        </div>
      </body>
    </html>
  )
}
